name = "Hugo ReFresh"
license = "MIT"
licenselink = "https://raw.githubusercontent.com/PippoRJ/hugo-refresh/master/LICENSE"
description = "A re-adaptation of the Hugo Fresh theme"
homepage = "https://github.com/PippoRJ/hugo-refresh"
tags = ["responsive", "blog", "light", "clean", "personal", "multilingual"]
features = ["blog", "responsive", "simple", "404"]
min_version = "0.45"

[author]
  name = "Roberto Jordaney"
  homepage = "https://github.com/PippoRJ"